language: cpp

compiler:
  - gcc

os: linux

before_script:
  - mkdir build
  - cd build
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt install gcc-10 g++-10 -y
  - cmake -D CMAKE_CXX_COMPILER=g++-10 -D CMAKE_C_COMPILER=gcc-10 ..

script:
  - cmake --build . --config Release