language: cpp

compiler:
  - clang

os: linux

before_script:
  - mkdir build
  - cd build
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  - cmake -D CMAKE_C_COMPILER=clang-10 -D CMAKE_CXX_COMPILER=clang++-10 ..

script:
  - cmake --build .